Test/task spec
gn2481/my_task_training pull request #4
Opened 2020-12-02 10:29 UTC by gn2481

任務功能的 feature_test，使用 Rspec & capybara
- 新增
- 修改
- 刪除

2020-12-02 11:04 UTC, chain329 commented on app/controllers/tasks_controller.rb
> +  def index
建議加上註解說明之後會有分頁

2020-12-02 11:04 UTC, chain329 commented on app/controllers/tasks_controller.rb
> +    @task.destroy
理論上要有失敗的情境

2020-12-02 11:04 UTC, chain329 commented on spec/features/task_spec.rb
> +  describe 'feature' do
需要描述這邊要測試的是什麼

2020-12-02 11:04 UTC, chain329 commented on spec/features/task_spec.rb
> +      )
應該拉出一個let才對，而且有裝factory_bot，應該要導入哦
```ruby
let!(:task) { create(:task, title: 'xxx', content: 'xxxx') }
```

2020-12-02 11:04 UTC, chain329 commented on spec/features/task_spec.rb
> +      expect(Task.count).to eq(2)      # 確認資料數
除了驗證count以外，應該要驗證新的一筆紀錄的title, content也要一樣

2020-12-02 11:04 UTC, chain329 commented on spec/features/task_spec.rb
> +      expect(Task.find_by(title:'capybara 修改 title')).not_to be_nil
`not_to be_nil`可以改用正向的`to be_present`

2020-12-10 04:47 UTC, chain329 approved these changes

2020-12-10 04:47 UTC, chain329 commented on spec/factories/tasks.rb
> +    # 這個沒什麼意思，就是想讓標題變得像任務一點
如果這個註解是在說title的話，通常會在上方，不會在下方

2020-12-10 06:20 UTC, gn2481 commented on spec/factories/tasks.rb
> +    # 這個沒什麼意思，就是想讓標題變得像任務一點
好的👌

2020-12-10 14:31 UTC, shes50103 requested changes

2020-12-10 14:31 UTC, shes50103 commented on spec/features/task_spec.rb
> +    end
before 裡面放
```ruby
expect(page).to have_content('新增任務') 
```
感覺比較奇怪，可以考慮就是測任務新增完就好
或者分兩個測試
一個測
```ruby
expect(page).to have_content('新增任務') 
```

一個測任務新增完後的
```ruby
expect(page).to have_content('任務新增成功！')     # 確認新增成功
expect(last_task_attrs).to eq(task_fields)    # 確認資料正確
expect(page).to have_content(task_fields[:title])
```

2020-12-10 14:31 UTC, shes50103 commented on spec/features/task_spec.rb
> +    end
像這種步驟很多的，可以考慮

```ruby
describe 'edit task' do
  before do
      visit tasks_path
      click_link('編輯')
      fill_in('任務名稱', with: task_fields[:title] )
      fill_in('任務內容', with: task_fields[:content] )
      click_button('送出')
  end

  scenario 'should update task' do 
    expect(page).to have_content('任務修改成功')
    expect(last_task_attrs).to eq(task_fields)
  end
end
```
把前置作業跟檢查兩件事分開

2020-12-10 14:31 UTC, shes50103 commented on .travis.yml
> +  - bundle exec rake db:migrate:reset RAILS_ENV=test
- bundle exec rake db:migrate:reset RAILS_ENV=test
應該也可以放到 before_script 裡面
這邊應該是直接 `rake db:migrate` 就可以了？

2020-12-10 14:31 UTC, shes50103 commented on .travis.yml
> +  - node -v
```
node -v
```
這個可以拿掉

2020-12-10 14:31 UTC, shes50103 commented on Gemfile
> +  gem 'shoulda-matchers'
**nitpick**

只有測試環境會需要用到的 `shoulda-matchers` 可考慮丟 `test ` 區塊
現在是丟在 `:development, :test` 區塊

2020-12-14 15:12 UTC, gn2481 commented on spec/features/task_spec.rb
> -      expect(page).to have_content('新增任務')      # 確認畫面為新增任務
決定不測這個了，反正如果畫面不對，下面一行也會失敗！

2020-12-18 06:33 UTC, shes50103 approved these changes

2020-12-18 06:34 UTC, merged